import { Header } from '../src/components/Header';
import TodosNavBar from '../src/components/TodosNavBar';
import './globals.css';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="h-full">
        <div className="flex flex-col w-full min-h-full">
          <Header />
          <div className="flex flex-row flex-1 w-full">
            {/* @ts-ignore */}
            <TodosNavBar />
            <div className="flex-1 m-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
