import { Header } from '../src/components/Header';
import TodosNavBar from '../src/components/TodosNavBar';
import './globals.css';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="h-full">
        <div className="flex flex-col min-h-full w-full">
          <Header />
          <div className="flex-row flex flex-1 w-full">
            <TodosNavBar />
            <div className="m-10 flex-1">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
